/*
 * MIT License
 *
 * Copyright (c) 2018 Stamina Development
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package pw.stamina.minecraftapi.item

import pw.stamina.minecraftapi.MinecraftApi

object Items {

    val AIR: Item
    val IRON_SHOVEL: Item
    val IRON_PICKAXE: Item
    val IRON_AXE: Item
    val FLINT_AND_STEEL: Item
    val APPLE: Item
    val BOW: Item
    val ARROW: Item
    val SPECTRAL_ARROW: Item
    val TIPPED_ARROW: Item
    val COAL: Item
    val DIAMOND: Item
    val IRON_INGOT: Item
    val GOLD_INGOT: Item
    val IRON_SWORD: Item
    val WOODEN_SWORD: Item
    val WOODEN_SHOVEL: Item
    val WOODEN_PICKAXE: Item
    val WOODEN_AXE: Item
    val STONE_SWORD: Item
    val STONE_SHOVEL: Item
    val STONE_PICKAXE: Item
    val STONE_AXE: Item
    val DIAMOND_SWORD: Item
    val DIAMOND_SHOVEL: Item
    val DIAMOND_PICKAXE: Item
    val DIAMOND_AXE: Item
    val STICK: Item
    val BOWL: Item
    val MUSHROOM_STEW: Item
    val GOLDEN_SWORD: Item
    val GOLDEN_SHOVEL: Item
    val GOLDEN_PICKAXE: Item
    val GOLDEN_AXE: Item
    val STRING: Item
    val FEATHER: Item
    val GUNPOWDER: Item
    val WOODEN_HOE: Item
    val STONE_HOE: Item
    val IRON_HOE: Item
    val DIAMOND_HOE: Item
    val GOLDEN_HOE: Item
    val WHEAT_SEEDS: Item
    val WHEAT: Item
    val BREAD: Item
    val LEATHER_HELMET: Item
    val LEATHER_CHESTPLATE: Item
    val LEATHER_LEGGINGS: Item
    val LEATHER_BOOTS: Item
    val CHAINMAIL_HELMET: Item
    val CHAINMAIL_CHESTPLATE: Item
    val CHAINMAIL_LEGGINGS: Item
    val CHAINMAIL_BOOTS: Item
    val IRON_HELMET: Item
    val IRON_CHESTPLATE: Item
    val IRON_LEGGINGS: Item
    val IRON_BOOTS: Item
    val DIAMOND_HELMET: Item
    val DIAMOND_CHESTPLATE: Item
    val DIAMOND_LEGGINGS: Item
    val DIAMOND_BOOTS: Item
    val GOLDEN_HELMET: Item
    val GOLDEN_CHESTPLATE: Item
    val GOLDEN_LEGGINGS: Item
    val GOLDEN_BOOTS: Item
    val FLINT: Item
    val PORKCHOP: Item
    val COOKED_PORKCHOP: Item
    val PAINTING: Item
    val GOLDEN_APPLE: Item
    val SIGN: Item
    val OAK_DOOR: Item
    val SPRUCE_DOOR: Item
    val BIRCH_DOOR: Item
    val JUNGLE_DOOR: Item
    val ACACIA_DOOR: Item
    val DARK_OAK_DOOR: Item
    val BUCKET: Item
    val WATER_BUCKET: Item
    val LAVA_BUCKET: Item
    val MINECART: Item
    val SADDLE: Item
    val IRON_DOOR: Item
    val REDSTONE: Item
    val SNOWBALL: Item
    val BOAT: Item
    val SPRUCE_BOAT: Item
    val BIRCH_BOAT: Item
    val JUNGLE_BOAT: Item
    val ACACIA_BOAT: Item
    val DARK_OAK_BOAT: Item
    val LEATHER: Item
    val MILK_BUCKET: Item
    val BRICK: Item
    val CLAY_BALL: Item
    val REEDS: Item
    val PAPER: Item
    val BOOK: Item
    val SLIME_BALL: Item
    val CHEST_MINECART: Item
    val FURNACE_MINECART: Item
    val EGG: Item
    val COMPASS: Item
    val FISHING_ROD: Item
    val CLOCK: Item
    val GLOWSTONE_DUST: Item
    val FISH: Item
    val COOKED_FISH: Item
    val DYE: Item
    val BONE: Item
    val SUGAR: Item
    val CAKE: Item
    val BED: Item
    val REPEATER: Item
    val COOKIE: Item
    val FILLED_MAP: Item
    val SHEARS: Item
    val MELON: Item
    val PUMPKIN_SEEDS: Item
    val MELON_SEEDS: Item
    val BEEF: Item
    val COOKED_BEEF: Item
    val CHICKEN: Item
    val COOKED_CHICKEN: Item
    val MUTTON: Item
    val COOKED_MUTTON: Item
    val RABBIT: Item
    val COOKED_RABBIT: Item
    val RABBIT_STEW: Item
    val RABBIT_FOOT: Item
    val RABBIT_HIDE: Item
    val ROTTEN_FLESH: Item
    val ENDER_PEARL: Item
    val BLAZE_ROD: Item
    val GHAST_TEAR: Item
    val GOLD_NUGGET: Item
    val NETHER_WART: Item
    val POTIONITEM: Item
    val SPLASH_POTION: Item
    val LINGERING_POTION: Item
    val GLASS_BOTTLE: Item
    val DRAGON_BREATH: Item
    val SPIDER_EYE: Item
    val FERMENTED_SPIDER_EYE: Item
    val BLAZE_POWDER: Item
    val MAGMA_CREAM: Item
    val BREWING_STAND: Item
    val CAULDRON: Item
    val ENDER_EYE: Item
    val SPECKLED_MELON: Item
    val SPAWN_EGG: Item
    val EXPERIENCE_BOTTLE: Item
    val FIRE_CHARGE: Item
    val WRITABLE_BOOK: Item
    val WRITTEN_BOOK: Item
    val EMERALD: Item
    val ITEM_FRAME: Item
    val FLOWER_POT: Item
    val CARROT: Item
    val POTATO: Item
    val BAKED_POTATO: Item
    val POISONOUS_POTATO: Item
    val MAP: Item
    val GOLDEN_CARROT: Item
    val SKULL: Item
    val CARROT_ON_A_STICK: Item
    val NETHER_STAR: Item
    val PUMPKIN_PIE: Item
    val FIREWORKS: Item
    val FIREWORK_CHARGE: Item
    val ENCHANTED_BOOK: Item
    val COMPARATOR: Item
    val NETHERBRICK: Item
    val QUARTZ: Item
    val TNT_MINECART: Item
    val HOPPER_MINECART: Item
    val ARMOR_STAND: Item
    val IRON_HORSE_ARMOR: Item
    val GOLDEN_HORSE_ARMOR: Item
    val DIAMOND_HORSE_ARMOR: Item
    val LEAD: Item
    val NAME_TAG: Item
    val COMMAND_BLOCK_MINECART: Item
    val RECORD_13: Item
    val RECORD_CAT: Item
    val RECORD_BLOCKS: Item
    val RECORD_CHIRP: Item
    val RECORD_FAR: Item
    val RECORD_MALL: Item
    val RECORD_MELLOHI: Item
    val RECORD_STAL: Item
    val RECORD_STRAD: Item
    val RECORD_WARD: Item
    val RECORD_11: Item
    val RECORD_WAIT: Item
    val PRISMARINE_SHARD: Item
    val PRISMARINE_CRYSTALS: Item
    val BANNER: Item
    val END_CRYSTAL: Item
    val SHIELD: Item
    val ELYTRA: Item
    val CHORUS_FRUIT: Item
    val CHORUS_FRUIT_POPPED: Item
    val BEETROOT_SEEDS: Item
    val BEETROOT: Item
    val BEETROOT_SOUP: Item
    val TOTEM_OF_UNDYING: Item
    val SHULKER_SHELL: Item
    val IRON_NUGGET: Item
    val KNOWLEDGE_BOOK: Item

    init {
        val registry = MinecraftApi.getAdapter().itemRegistry

        AIR = registry.getRegisteredItemOrAir("air")
        IRON_SHOVEL = registry.getRegisteredItemOrAir("iron_shovel")
        IRON_PICKAXE = registry.getRegisteredItemOrAir("iron_pickaxe")
        IRON_AXE = registry.getRegisteredItemOrAir("iron_axe")
        FLINT_AND_STEEL = registry.getRegisteredItemOrAir("flint_and_steel")
        APPLE = registry.getRegisteredItemOrAir("apple")
        BOW = registry.getRegisteredItemOrAir("bow")
        ARROW = registry.getRegisteredItemOrAir("arrow")
        SPECTRAL_ARROW = registry.getRegisteredItemOrAir("spectral_arrow")
        TIPPED_ARROW = registry.getRegisteredItemOrAir("tipped_arrow")
        COAL = registry.getRegisteredItemOrAir("coal")
        DIAMOND = registry.getRegisteredItemOrAir("diamond")
        IRON_INGOT = registry.getRegisteredItemOrAir("iron_ingot")
        GOLD_INGOT = registry.getRegisteredItemOrAir("gold_ingot")
        IRON_SWORD = registry.getRegisteredItemOrAir("iron_sword")
        WOODEN_SWORD = registry.getRegisteredItemOrAir("wooden_sword")
        WOODEN_SHOVEL = registry.getRegisteredItemOrAir("wooden_shovel")
        WOODEN_PICKAXE = registry.getRegisteredItemOrAir("wooden_pickaxe")
        WOODEN_AXE = registry.getRegisteredItemOrAir("wooden_axe")
        STONE_SWORD = registry.getRegisteredItemOrAir("stone_sword")
        STONE_SHOVEL = registry.getRegisteredItemOrAir("stone_shovel")
        STONE_PICKAXE = registry.getRegisteredItemOrAir("stone_pickaxe")
        STONE_AXE = registry.getRegisteredItemOrAir("stone_axe")
        DIAMOND_SWORD = registry.getRegisteredItemOrAir("diamond_sword")
        DIAMOND_SHOVEL = registry.getRegisteredItemOrAir("diamond_shovel")
        DIAMOND_PICKAXE = registry.getRegisteredItemOrAir("diamond_pickaxe")
        DIAMOND_AXE = registry.getRegisteredItemOrAir("diamond_axe")
        STICK = registry.getRegisteredItemOrAir("stick")
        BOWL = registry.getRegisteredItemOrAir("bowl")
        MUSHROOM_STEW = registry.getRegisteredItemOrAir("mushroom_stew")
        GOLDEN_SWORD = registry.getRegisteredItemOrAir("golden_sword")
        GOLDEN_SHOVEL = registry.getRegisteredItemOrAir("golden_shovel")
        GOLDEN_PICKAXE = registry.getRegisteredItemOrAir("golden_pickaxe")
        GOLDEN_AXE = registry.getRegisteredItemOrAir("golden_axe")
        STRING = registry.getRegisteredItemOrAir("string")
        FEATHER = registry.getRegisteredItemOrAir("feather")
        GUNPOWDER = registry.getRegisteredItemOrAir("gunpowder")
        WOODEN_HOE = registry.getRegisteredItemOrAir("wooden_hoe")
        STONE_HOE = registry.getRegisteredItemOrAir("stone_hoe")
        IRON_HOE = registry.getRegisteredItemOrAir("iron_hoe")
        DIAMOND_HOE = registry.getRegisteredItemOrAir("diamond_hoe")
        GOLDEN_HOE = registry.getRegisteredItemOrAir("golden_hoe")
        WHEAT_SEEDS = registry.getRegisteredItemOrAir("wheat_seeds")
        WHEAT = registry.getRegisteredItemOrAir("wheat")
        BREAD = registry.getRegisteredItemOrAir("bread")
        LEATHER_HELMET = registry.getRegisteredItemOrAir("leather_helmet")
        LEATHER_CHESTPLATE = registry.getRegisteredItemOrAir("leather_chestplate")
        LEATHER_LEGGINGS = registry.getRegisteredItemOrAir("leather_leggings")
        LEATHER_BOOTS = registry.getRegisteredItemOrAir("leather_boots")
        CHAINMAIL_HELMET = registry.getRegisteredItemOrAir("chainmail_helmet")
        CHAINMAIL_CHESTPLATE = registry.getRegisteredItemOrAir("chainmail_chestplate")
        CHAINMAIL_LEGGINGS = registry.getRegisteredItemOrAir("chainmail_leggings")
        CHAINMAIL_BOOTS = registry.getRegisteredItemOrAir("chainmail_boots")
        IRON_HELMET = registry.getRegisteredItemOrAir("iron_helmet")
        IRON_CHESTPLATE = registry.getRegisteredItemOrAir("iron_chestplate")
        IRON_LEGGINGS = registry.getRegisteredItemOrAir("iron_leggings")
        IRON_BOOTS = registry.getRegisteredItemOrAir("iron_boots")
        DIAMOND_HELMET = registry.getRegisteredItemOrAir("diamond_helmet")
        DIAMOND_CHESTPLATE = registry.getRegisteredItemOrAir("diamond_chestplate")
        DIAMOND_LEGGINGS = registry.getRegisteredItemOrAir("diamond_leggings")
        DIAMOND_BOOTS = registry.getRegisteredItemOrAir("diamond_boots")
        GOLDEN_HELMET = registry.getRegisteredItemOrAir("golden_helmet")
        GOLDEN_CHESTPLATE = registry.getRegisteredItemOrAir("golden_chestplate")
        GOLDEN_LEGGINGS = registry.getRegisteredItemOrAir("golden_leggings")
        GOLDEN_BOOTS = registry.getRegisteredItemOrAir("golden_boots")
        FLINT = registry.getRegisteredItemOrAir("flint")
        PORKCHOP = registry.getRegisteredItemOrAir("porkchop")
        COOKED_PORKCHOP = registry.getRegisteredItemOrAir("cooked_porkchop")
        PAINTING = registry.getRegisteredItemOrAir("painting")
        GOLDEN_APPLE = registry.getRegisteredItemOrAir("golden_apple")
        SIGN = registry.getRegisteredItemOrAir("sign")
        OAK_DOOR = registry.getRegisteredItemOrAir("wooden_door")
        SPRUCE_DOOR = registry.getRegisteredItemOrAir("spruce_door")
        BIRCH_DOOR = registry.getRegisteredItemOrAir("birch_door")
        JUNGLE_DOOR = registry.getRegisteredItemOrAir("jungle_door")
        ACACIA_DOOR = registry.getRegisteredItemOrAir("acacia_door")
        DARK_OAK_DOOR = registry.getRegisteredItemOrAir("dark_oak_door")
        BUCKET = registry.getRegisteredItemOrAir("bucket")
        WATER_BUCKET = registry.getRegisteredItemOrAir("water_bucket")
        LAVA_BUCKET = registry.getRegisteredItemOrAir("lava_bucket")
        MINECART = registry.getRegisteredItemOrAir("minecart")
        SADDLE = registry.getRegisteredItemOrAir("saddle")
        IRON_DOOR = registry.getRegisteredItemOrAir("iron_door")
        REDSTONE = registry.getRegisteredItemOrAir("redstone")
        SNOWBALL = registry.getRegisteredItemOrAir("snowball")
        BOAT = registry.getRegisteredItemOrAir("boat")
        SPRUCE_BOAT = registry.getRegisteredItemOrAir("spruce_boat")
        BIRCH_BOAT = registry.getRegisteredItemOrAir("birch_boat")
        JUNGLE_BOAT = registry.getRegisteredItemOrAir("jungle_boat")
        ACACIA_BOAT = registry.getRegisteredItemOrAir("acacia_boat")
        DARK_OAK_BOAT = registry.getRegisteredItemOrAir("dark_oak_boat")
        LEATHER = registry.getRegisteredItemOrAir("leather")
        MILK_BUCKET = registry.getRegisteredItemOrAir("milk_bucket")
        BRICK = registry.getRegisteredItemOrAir("brick")
        CLAY_BALL = registry.getRegisteredItemOrAir("clay_ball")
        REEDS = registry.getRegisteredItemOrAir("reeds")
        PAPER = registry.getRegisteredItemOrAir("paper")
        BOOK = registry.getRegisteredItemOrAir("book")
        SLIME_BALL = registry.getRegisteredItemOrAir("slime_ball")
        CHEST_MINECART = registry.getRegisteredItemOrAir("chest_minecart")
        FURNACE_MINECART = registry.getRegisteredItemOrAir("furnace_minecart")
        EGG = registry.getRegisteredItemOrAir("egg")
        COMPASS = registry.getRegisteredItemOrAir("compass")
        FISHING_ROD = registry.getRegisteredItemOrAir("fishing_rod")
        CLOCK = registry.getRegisteredItemOrAir("clock")
        GLOWSTONE_DUST = registry.getRegisteredItemOrAir("glowstone_dust")
        FISH = registry.getRegisteredItemOrAir("fish")
        COOKED_FISH = registry.getRegisteredItemOrAir("cooked_fish")
        DYE = registry.getRegisteredItemOrAir("dye")
        BONE = registry.getRegisteredItemOrAir("bone")
        SUGAR = registry.getRegisteredItemOrAir("sugar")
        CAKE = registry.getRegisteredItemOrAir("cake")
        BED = registry.getRegisteredItemOrAir("bed")
        REPEATER = registry.getRegisteredItemOrAir("repeater")
        COOKIE = registry.getRegisteredItemOrAir("cookie")
        FILLED_MAP = registry.getRegisteredItemOrAir("filled_map")
        SHEARS = registry.getRegisteredItemOrAir("shears")
        MELON = registry.getRegisteredItemOrAir("melon")
        PUMPKIN_SEEDS = registry.getRegisteredItemOrAir("pumpkin_seeds")
        MELON_SEEDS = registry.getRegisteredItemOrAir("melon_seeds")
        BEEF = registry.getRegisteredItemOrAir("beef")
        COOKED_BEEF = registry.getRegisteredItemOrAir("cooked_beef")
        CHICKEN = registry.getRegisteredItemOrAir("chicken")
        COOKED_CHICKEN = registry.getRegisteredItemOrAir("cooked_chicken")
        MUTTON = registry.getRegisteredItemOrAir("mutton")
        COOKED_MUTTON = registry.getRegisteredItemOrAir("cooked_mutton")
        RABBIT = registry.getRegisteredItemOrAir("rabbit")
        COOKED_RABBIT = registry.getRegisteredItemOrAir("cooked_rabbit")
        RABBIT_STEW = registry.getRegisteredItemOrAir("rabbit_stew")
        RABBIT_FOOT = registry.getRegisteredItemOrAir("rabbit_foot")
        RABBIT_HIDE = registry.getRegisteredItemOrAir("rabbit_hide")
        ROTTEN_FLESH = registry.getRegisteredItemOrAir("rotten_flesh")
        ENDER_PEARL = registry.getRegisteredItemOrAir("ender_pearl")
        BLAZE_ROD = registry.getRegisteredItemOrAir("blaze_rod")
        GHAST_TEAR = registry.getRegisteredItemOrAir("ghast_tear")
        GOLD_NUGGET = registry.getRegisteredItemOrAir("gold_nugget")
        NETHER_WART = registry.getRegisteredItemOrAir("nether_wart")
        POTIONITEM = registry.getRegisteredItemOrAir("potion")
        SPLASH_POTION = registry.getRegisteredItemOrAir("splash_potion")
        LINGERING_POTION = registry.getRegisteredItemOrAir("lingering_potion")
        GLASS_BOTTLE = registry.getRegisteredItemOrAir("glass_bottle")
        DRAGON_BREATH = registry.getRegisteredItemOrAir("dragon_breath")
        SPIDER_EYE = registry.getRegisteredItemOrAir("spider_eye")
        FERMENTED_SPIDER_EYE = registry.getRegisteredItemOrAir("fermented_spider_eye")
        BLAZE_POWDER = registry.getRegisteredItemOrAir("blaze_powder")
        MAGMA_CREAM = registry.getRegisteredItemOrAir("magma_cream")
        BREWING_STAND = registry.getRegisteredItemOrAir("brewing_stand")
        CAULDRON = registry.getRegisteredItemOrAir("cauldron")
        ENDER_EYE = registry.getRegisteredItemOrAir("ender_eye")
        SPECKLED_MELON = registry.getRegisteredItemOrAir("speckled_melon")
        SPAWN_EGG = registry.getRegisteredItemOrAir("spawn_egg")
        EXPERIENCE_BOTTLE = registry.getRegisteredItemOrAir("experience_bottle")
        FIRE_CHARGE = registry.getRegisteredItemOrAir("fire_charge")
        WRITABLE_BOOK = registry.getRegisteredItemOrAir("writable_book")
        WRITTEN_BOOK = registry.getRegisteredItemOrAir("written_book")
        EMERALD = registry.getRegisteredItemOrAir("emerald")
        ITEM_FRAME = registry.getRegisteredItemOrAir("item_frame")
        FLOWER_POT = registry.getRegisteredItemOrAir("flower_pot")
        CARROT = registry.getRegisteredItemOrAir("carrot")
        POTATO = registry.getRegisteredItemOrAir("potato")
        BAKED_POTATO = registry.getRegisteredItemOrAir("baked_potato")
        POISONOUS_POTATO = registry.getRegisteredItemOrAir("poisonous_potato")
        MAP = registry.getRegisteredItemOrAir("map")
        GOLDEN_CARROT = registry.getRegisteredItemOrAir("golden_carrot")
        SKULL = registry.getRegisteredItemOrAir("skull")
        CARROT_ON_A_STICK = registry.getRegisteredItemOrAir("carrot_on_a_stick")
        NETHER_STAR = registry.getRegisteredItemOrAir("nether_star")
        PUMPKIN_PIE = registry.getRegisteredItemOrAir("pumpkin_pie")
        FIREWORKS = registry.getRegisteredItemOrAir("fireworks")
        FIREWORK_CHARGE = registry.getRegisteredItemOrAir("firework_charge")
        ENCHANTED_BOOK = registry.getRegisteredItemOrAir("enchanted_book")
        COMPARATOR = registry.getRegisteredItemOrAir("comparator")
        NETHERBRICK = registry.getRegisteredItemOrAir("netherbrick")
        QUARTZ = registry.getRegisteredItemOrAir("quartz")
        TNT_MINECART = registry.getRegisteredItemOrAir("tnt_minecart")
        HOPPER_MINECART = registry.getRegisteredItemOrAir("hopper_minecart")
        ARMOR_STAND = registry.getRegisteredItemOrAir("armor_stand")
        IRON_HORSE_ARMOR = registry.getRegisteredItemOrAir("iron_horse_armor")
        GOLDEN_HORSE_ARMOR = registry.getRegisteredItemOrAir("golden_horse_armor")
        DIAMOND_HORSE_ARMOR = registry.getRegisteredItemOrAir("diamond_horse_armor")
        LEAD = registry.getRegisteredItemOrAir("lead")
        NAME_TAG = registry.getRegisteredItemOrAir("name_tag")
        COMMAND_BLOCK_MINECART = registry.getRegisteredItemOrAir("command_block_minecart")
        RECORD_13 = registry.getRegisteredItemOrAir("record_13")
        RECORD_CAT = registry.getRegisteredItemOrAir("record_cat")
        RECORD_BLOCKS = registry.getRegisteredItemOrAir("record_blocks")
        RECORD_CHIRP = registry.getRegisteredItemOrAir("record_chirp")
        RECORD_FAR = registry.getRegisteredItemOrAir("record_far")
        RECORD_MALL = registry.getRegisteredItemOrAir("record_mall")
        RECORD_MELLOHI = registry.getRegisteredItemOrAir("record_mellohi")
        RECORD_STAL = registry.getRegisteredItemOrAir("record_stal")
        RECORD_STRAD = registry.getRegisteredItemOrAir("record_strad")
        RECORD_WARD = registry.getRegisteredItemOrAir("record_ward")
        RECORD_11 = registry.getRegisteredItemOrAir("record_11")
        RECORD_WAIT = registry.getRegisteredItemOrAir("record_wait")
        PRISMARINE_SHARD = registry.getRegisteredItemOrAir("prismarine_shard")
        PRISMARINE_CRYSTALS = registry.getRegisteredItemOrAir("prismarine_crystals")
        BANNER = registry.getRegisteredItemOrAir("banner")
        END_CRYSTAL = registry.getRegisteredItemOrAir("end_crystal")
        SHIELD = registry.getRegisteredItemOrAir("shield")
        ELYTRA = registry.getRegisteredItemOrAir("elytra")
        CHORUS_FRUIT = registry.getRegisteredItemOrAir("chorus_fruit")
        CHORUS_FRUIT_POPPED = registry.getRegisteredItemOrAir("chorus_fruit_popped")
        BEETROOT_SEEDS = registry.getRegisteredItemOrAir("beetroot_seeds")
        BEETROOT = registry.getRegisteredItemOrAir("beetroot")
        BEETROOT_SOUP = registry.getRegisteredItemOrAir("beetroot_soup")
        TOTEM_OF_UNDYING = registry.getRegisteredItemOrAir("totem_of_undying")
        SHULKER_SHELL = registry.getRegisteredItemOrAir("shulker_shell")
        IRON_NUGGET = registry.getRegisteredItemOrAir("iron_nugget")
        KNOWLEDGE_BOOK = registry.getRegisteredItemOrAir("knowledge_book")
    }
}
